title                       : "Getting started in DPOA"
author                      : CMS DPOA team  # The author of the book
logo                        : logo.png
execute:
  execute_notebooks: "off"
#######################################################################################
# HTML-specific settings
html:
  favicon                   : logo.png  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  
repository:
  url                       : https://github.com/cms-dpoa/cms-dpoa-getting-started  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : "master"  # Which branch of the repository should be used when creating links
#######################################################################################
# Advanced and power-user settings
sphinx:

  # A list of extra extensions to load by Sphinx (added to those already used by JB).
  config:
      html_show_copyright: false
      language: en
